---
- name: node-1
  provider: virtualbox
  box: ubuntu/trusty64
  cpu: 1
  mem: 512
  ip: 10.17.0.201
  shared_folders:
  - src: ./scripts
    dest: /Vagrant_Shared
    options:
      :create: true
      :owner: root
      :group: root
